---
name: Building README.md
on: 
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@master
      - name: Building itself
        run: make build.release
      - name: Building README.md
        run: make README.md TARGET=release
      - name: Committing README.md
        run: make git-me
