---
name: Building Readme.me
on: push
jobs:
  build:
    # runs-on: crystallang/crystal:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building self
        run: make build
      - name: Building README.md
        run: make README.md
