---
name: Building Readme.me

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: crystallang/crystal:latest
  steps:
    - uses: actions/checkout@v3

    - name: Building self
      run: make build
    - name: Building README.md
      run: make README.md
