---
name: Building README.md
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@master
      - name: Update Libs
        run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev
      - name: Building itself
        run: make build
      - name: Building README.md
        run: make README.md
      - name: Commit README.md
        run: |
          git config --global --add safe.directory /__w/readme/readme
          git config --global user.name 'Github Action'
          git config --global user.email 'workflow@users.noreply.github.com'
          git add . || exit 0
          git commit -m "Automated README.md" || exit 0
          git push || exit 0
      - name: Uploading Assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/readme
          asset_name: readme-${{ github.event.release.tag_name }}-linux-x86_64
          asset_content_type: binary/octet-stream
