---
name: Building for Release
on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  relase:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@master
      - name: Debuging
        run: |
          echo ${{ github.ref_name }}
          env
      - name: Update Libs
        run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev
      - name: Building itself
        run: make build.release
      - name: Building README.md
        run: make README.md
      - name: Commit README.md
        run: make git-me
      - name: Making sure there is a relase note set up
        run: make changelog/${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/changelog/${{ github.ref_name}}.md
          files: ./bin/readme
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Building
        run: make docker.build
      - name: Pushing
        run: docker.push
      # - name: Login to DockerHub
        # uses: docker/login-action@v2
        # with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
        # uses: docker/build-push-action@v3
        # with:
          # push: true
          # tags: user/app:latest
