---
name: Building for Release
on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  relase:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@master
      - name: Debuging
        run: |
          echo ${{ github.ref_name }}
          env
      - name: Update Libs
        run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev
      - name: Building itself
        run: make build.release
      - name: Building README.md
        run: make README.md
      - name: Commit README.md
        run: make git-me
      - name: Making sure there is a relase note set up
        run: make changelog/${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/changelog/${{ github.ref_name}}.md
          files: ./bin/readme
